export const projects = [
  {
    name: "Sveltedex",
    subtitle: "Pokemon Encyclopedia",
    image: "/assets/img/sveltedex.png",
    fullImage: "/assets/img/sveltedex-full.png",
    typeline: "Svelte, Firebase",
    fullTypeline: "Svelte, JavaScript/HTML/CSS, Firebase",
    backgroundColor: `linear-gradient(to bottom, #e35f48, #e4e0ba);`,
    shortDesc:
      "A Pokemon encyclopedia modeled after the in-game Pokedex tool; created with Svelte as frontend framework and hosted with Firebase",
    description:
      "A Pokemon encyclopedia modeled after the in-game Pokedex tool, containing entries for each Pokemon up the 8th Generation; created with Svelte as a frontend framework and hosted with Firebase, with data set sourced from kaggle.com.",
    footerText: "© 2022",
    projectLink: "https://sveltedex.web.app/",
    githubLink: "https://github.com/ZacAllen/sveltedex-app",
  },

  {
    name: "DreamyBot",
    subtitle: "Discord Bot",
    image: "/assets/img/dreamybot.png",
    fullImage: "/assets/img/dreamybot-full.png",
    typeline: "JS, discord.js, OpenAI API",
    fullTypeline: "JavaScript, discord.js, OpenAI API, Youtube API, Huggingface, Inference API",
    backgroundColor: `linear-gradient(to bottom, #302f3c, #3c2ea0);`,
    shortDesc:
      "Discord bot with multiple functionalities, mainly voice channel youtube playback and ChatGPT + Stable Diffusion integration.",
    description:
      "Discord bot with multiple functionalities, including voice channel youtube playback, TTS speech generation, ChatGPT text prompting, and image generation with DALL-E 3 or the FLUX.1 Stable Diffusion model.",
    footerText: "© 2023",
    projectLink: false,
    githubLink: "https://github.com/ZacAllen/DreamyBot",
  },
  {
    name: "Portfolio Website",
    subtitle: "Portfolio",
    image: "/assets/img/personal website.png",
    fullImage: "/assets/img/personal website-full.png",
    typeline: "Next.js, Netlify",
    fullTypeline: "Next.js, Netlify, TailwindCSS, MaterialUI",
    backgroundColor: `linear-gradient(to bottom, #485A9A, #3A4634);`,
    shortDesc: "This Portfolio Website, created with Next.js and hosted with Netlify.",
    description:
      "This portfolio website, zachsallen.com, created with Next.js and hosted with Netlify, with TailwindCSS and MaterialUI for styling. Animations were created with Motion (formerly Framer Motion).",
    footerText: "© 2025",
    projectLink: false,
    githubLink: "https://github.com/ZacAllen/portfolio24",
  },
  {
    name: "Numberle",
    subtitle: "Worlde Parody",
    image: "/assets/img/numberle.png",
    fullImage: "/assets/img/numberle-full.png",
    typeline: "ReactJS, Netlify",
    fullTypeline: "ReactJS, Netlify",
    backgroundColor: `linear-gradient(to bottom, #38b24a, #cbbf55);`,
    shortDesc: "A parody of the popular puzzle game Wordle, made in React and hosted with Netlify.",
    description: "A small SPA web-app parody of the popular puzzle game Wordle, made in React and hosted with Netlify.",
    projectLink: "https://numberle.netlify.app/",
    githubLink: "https://github.com/ZacAllen/numberle",
    footerText: "© 2022",
  },
  {
    name: "Copycat",
    image: "/assets/img/copycat.png",
    fullImage: "/assets/img/copycat-full.png",
    typeline: "Expo, React Native",
    fullTypeline: "Expo, React Native",
    backgroundColor: `linear-gradient(to bottom, #faed84, #bacee4);`,
    shortDesc: "Project in development, coming soon.",
    description: "",
    footerText: "© 2025",
    projectLink: false,
    githubLink: false,
  },
];
